namespace Funcs {
	export type IGProfile = {
		logging_page_id: string;
		show_suggested_profiles: boolean;
		show_follow_dialog: boolean;
		graphql: {
			user: {
				biography: string;
				blocked_by_viewer: boolean;
				restricted_by_viewer: boolean;
				country_block: boolean;
				external_url: string;
				external_url_linkshmmied: string;
				edge_followed_by: {
					count: number;
				};
				fbid: string;
				followed_by_viewer: boolean;
				edge_follow: {
					count: number;
				};
				follows_viewer: boolean;
				full_name: string;
				id: string;
				is_private: boolean;
				is_verified: boolean;
				profile_pic_url: string;
				profile_pic_url_hd: string;
				username: string;
				edge_owner_to_timeline_media: {
					count: number;
				};
			};
		};
	};

	export type Subreddit = {
		user_flair_background_color: any;
		submit_text_html: string;
		restrict_posting: boolean;
		user_is_banned: any;
		free_form_reports: boolean;
		wiki_enabled: boolean;
		user_is_muted: any;
		user_can_flair_in_sr: any;
		display_name: string;
		header_img: string;
		title: string;
		allow_galleries: boolean;
		icon_size: number[];
		primary_color: string;
		active_user_count: number;
		icon_img: string;
		display_name_prefixed: string;
		accounts_active: number;
		public_traffic: boolean;
		subscribers: number;
		user_flair_richtext: any[];
		videostream_links_count: number;
		name: string;
		quarantine: boolean;
		hide_ads: boolean;
		prediction_leaderboard_entry_type: string;
		emojis_enabled: boolean;
		advertiser_category: string;
		public_description: string;
		comment_score_hide_mins: number;
		allow_predictions: boolean;
		user_has_favorited: any;
		user_flair_template_id: any;
		community_icon: string;
		banner_background_image: string;
		original_content_tag_enabled: boolean;
		community_reviewd: boolean;
		submit_text: string;
		description_html: string;
		spoilers_enabled: boolean;
		header_title: string;
		header_size: number[];
		user_flair_position: string;
		all_original_content: boolean;
		has_menu_widget: boolean;
		is_enrolled_in_new_modmail: any;
		key_color: string;
		can_assign_user_flair: boolean;
		created: number;
		wls: number;
		show_media_preview: boolean;
		submission_type: string;
		user_is_subscribed: any;
		disable_contributor_requests: boolean;
		allow_videogifs: boolean;
		user_flair_type: string;
		allow_polls: boolean;
		collapse_deleted_comments: boolean;
		public_description_html: string;
		allow_videos: boolean;
		is_crosspostable_subreddit: boolean;
		notification_level: any;
		can_assign_link_flair: boolean;
		accounts_active_is_fuzzed: boolean;
		submit_text_label: string;
		link_flair_position: string;
		user_sr_flair_enabled: any;
		user_flair_enabled_in_sr: boolean;
		allow_discovery: boolean;
		user_sr_theme_enabled: boolean;
		link_flair_enabled: boolean;
		subreddit_type: string;
		suggested_comment_sort: any;
		banner_img: string;
		user_flair_text: any;
		banner_background_color: string;
		show_media: boolean;
		id: string;
		user_is_moderator: boolean;
		over18: boolean;
		description: string;
		submit_link_label: string;
		user_flair_text_color: any;
		restrict_commenting: boolean;
		allow_images: boolean;
		lang: string;
		whitelist_status: string;
		url: string;
		created_utc: number;
		banner_size: any;
		mobile_banner_img: string;
		user_is_contributor: any;
		allow_predictions_tournament: boolean;
	};

	export type User = {
		kind: string;
		data: {
			is_employee: boolean;
			is_friend: boolean;
			subreddit: {
				default_set: boolean;
				user_is_contributor: any;
				banner_img: string;
				restrict_posting: true;
				user_is_banned: any;
				free_form_reports: boolean;
				community_icon: any;
				show_media: boolean;
				icon_color: string;
				display_name: string;
				header_img: any;
				title: string;
				priveous_names: string[];
				over_18: boolean;
				icon_size: number[];
				primary_color: string;
				icon_img: string;
				description: string;
				submit_link_label: string;
				header_size: any;
				is_default_icon: boolean;
				link_flair_position: string;
				display_name_prefixed: string;
				key_color: string;
				name: string;
				is_default_banner: boolean;
				url: string;
				quarantine: boolean;
				banner_size: any;
				user_is_moderator: any;
				public_description: string;
				link_flair_enabled: boolean;
				disable_contributor_requests: boolean;
				subreddit_type: string;
				user_is_subscriber: any;
			};
			snoovatar_size: any;
			awardee_karma: number;
			id: string;
			verified: boolean;
			is_gold: boolean;
			is_mod: boolean;
			awarder_karma: number;
			has_verified_email: boolean;
			icon_img: string;
			hide_from_robots: boolean;
			link_karma: number;
			total_karma: number;
			pref_show_snoovatar: boolean;
			name: string;
			created: number;
			created_utc: number;
			snoovatar_img: string;
			comment_karma: number;
			has_subscribed: boolean;
		};
	};
}

export = Funcs;
